### ISSUE TITLE
Slack community link is expired

### ISSUE THREAD

**Issue by netgio** [mulesoft-labs/data-weave-rfc#37]
The link in the README.md is expired. 
`Join our community [Slack](https://join.slack.com/t/dataweavelanguage/shared_invite/zt-1f3xmq8n6-MVoUj7dDamxyu_Zyf62ERQ)`

**Comment by netgio** [comment]
Same error for the link on the landing page - https://dataweave.mulesoft.com/

**Comment by machaval** [comment]
Thanks! We will try to fix this ASAP

**Comment by afelisatti** [comment]
Thanks, @netgio. We've updated it here and are also in the process of updating the website and our CLI repo.
