### ISSUE TITLE
Getting wrong error message in vscode but not in the playground

### ISSUE THREAD

**Issue by alexandramartinez** [mulesoft-labs/data-weave-rfc#55]
This code works correctly from the playground but in vscode it gives me this error:

```
Expecting Type: `Move`, but got: `Boolean` at `[*]`.
	|-- From: `Array<Move>`

19| 		('up') if (yDistance <= -1)
                 ^^^^^^^^^^^^^^^
Location:
MyMapping (line: 19, column:14)
```

code:

```dwl
%dw 2.0
output application/json

type Point = {
    x: Number,
    y: Number
}
type Move = "up" | "down" | "left" | "right"

var moves:Array<Move> = ["up", "down", "left", "right"]
fun whereIs(point_1:Point, point_2:Point):Array<Move> = do {
	var xDistance = point_1.x - point_2.x
    var yDistance = point_1.y - point_2.y
	---
	[
		('left') if (xDistance >= 1),
		('right') if (xDistance <= -1),
		('down') if (yDistance >= 1),
		('up') if (yDistance <= -1)
	]
}
---
moves 
```

screenshot:

![image](https://user-images.githubusercontent.com/3922764/222522980-a7da94a4-8d9c-4960-95ef-9c8fcccf7aee.png)
![image](https://user-images.githubusercontent.com/3922764/222523010-d814b7bd-9058-4d62-af7b-2cef42cb688f.png)

**Comment by alexandramartinez** [comment]
plus, colors look wrong - 
![image](https://user-images.githubusercontent.com/3922764/222523711-5abac46e-0084-495d-b467-92fb5a72dddd.png)

**Comment by machaval** [comment]
Hi Alex, thanks for the report, can you attach the project. The reason that they preview may fail and not the code editor is that preview uses the runtime that you have configured in your pom.xml and the editor uses a version that is embedded (is a very new version). So this may be something that we already fixed but yet not being released

**Comment by alexandramartinez** [comment]
For sure! here it is.

It has more code now cause I'm modifying the code, but the `whereIs` function is on line 54.
The code works without the `<Move>` in the return type, but it should be working (like in the playground)

```dwl
fun whereIs(point_1:Point, point_2:Point):Array<Move> = do {
```

[battlesnake.zip](https://github.com/mulesoft-labs/data-weave-rfc/files/10875136/battlesnake.zip)

**Comment by machaval** [comment]
If you try this version 2.5.0-20230207 it should work as you expect

**Comment by alexandramartinez** [comment]
worked with 2.5.0-20221220
thanks!!
